---
title: "Week-01-Notes"
author: "Andrew Nalundasan"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Week 1 Overview

+ 6 credit course
+ query assignments due from the starting line
+ sort out technical aspects immediately
+ ensure able to access SQL Server
+ SQL Server Name:
    
    + ITS-ALBRS-DB1.SEATTLEU.EDU
    + ADVENTUREWORKS2017 <- main DB we'll be working with
    
+ naming convention:

    + as_22SQ_(your initials)_(database name)
    + e.g.for Jose Rodriguez: 
        + as_22SQ_jr_salesorder
        + as_22SQ_jr_recipes
        
+ access SQL server via Albers virtual desktop: 

    + https://www.seattleu.edu/its/collab/virtual-desktop/
    
+ Every week: 

    + overview video
    + go over queries
    + insights and recommendations
    + feedback
    + adjustment to assignments
    
    
# Overview and Hello

+ databases
+ objectives:

    + data types
        + Structured
        + NoSQL
        + Unstructured Big Data
    + DBMS
        + Collect and store data
        + index data to access it
        + protect the data
        + scalability
        + de-mystify the complexity of DBMS
    + Query Languages and Tools
        + T-SQL for SQL Server
        + MQL for MongoDB (unstructured)
        + Hadoop for unstructured data types
        + Power BI
    + Understand how data is stored and managed, and how to write queries to access that data


# What is Corporate Data

+ business related information used to help corporation be more successful and profitable
+ ignores data that adds no business / corporate value
+ transactional data - historically provided the most business value
+ changing data formats

    + semi-structured data (social media)
    + structured data
    + unstructured data
        + analyze big data and determine sentiment

+ new norm is no longer looking at transactional and structured data
+ must keep asking questions as an analyst
+ DATA ADVENTURERS!!!


# Course Logistics

+ Everything will be on canvas
+ 10 modules for the quarter. Each module will have: 

    + overview video
    + lecture videos
    + examples
    + "Take a break" - get your hands dirty
        + includes assignments to submit
        + provides information about how to knock out the weekly assignment
    + weekly assignment
    
+ SQL Queries for Mere Mortals - because it's awesome :) 

    + Focuses on data querying and manipulation <- what OMSBA is all about!
    
+ Mongo DB
+ Architecting Modern Data Platforms - hadoop

+ this will be very hands-on technical class
+ It will combine database theory and design with examples and hands-on query building
+ Grading

    1. weekly assignments
    2. Exams - midterm, final
    3. DTC

# Introductions

+ never underestimate the power of a strong network
+ start the journey by looking at the end requirements
+ know what the plant management system needed in order to run the plant
+ build the DBMS to bring it all together intelligently


# Database Systems

+ Database

    + Collections of data sets stored in a systematic way
    + document store
    + data warehouse
    + data mart
    
+ Data Lake

    + Require less up front management of the data
    + Open system that receives all kinds of native in their native format
        + unstructured
    + typically at high-velocity, from a variety of sources
    
+ Types of data

    1. Structured (Relational)
        + Rigid scheme-based, for rows and columns
        + Traditional business DBs
        + Known and maintained format
        + Products / sales / inventory / warehouse
        + DBMS required
            + Heavyweight, server-based systems
            + Controls all access and data integrity
            + Fast and scale upward
            + SQL Server / Oracle / MySQL / PostgreSQL
    2. Semi-structured (NoSQL <- "Not Only SQL")
        + non-relational and schema-less
        + Mobile and Web Applications
        + Seld-describing documents, graphs, and key-values
        + Facebook, OneNote, EverNote
        + DBMS not required
            + Lightweight, mobile
            + Works across platforms and devices
            + Places data logic and integrity on the application
            + JSON / MongoDB / Redis / Cassandra
            + Able to make changes to the data going forward, without making changes to historical data (due to semi-structured format)
    3. Unstructured (Big Data)
        + Unknown or changing structure
        + **All data has some kind of structure**, but we may not know it or control it or the structure varies
        + Can be pretty much any kind of data
        + **Sensor data** / social media posts / text/ binary
        + Sophisticated tools required
            + Hadoop / HBase / Google Big QUery / DynamoDB
            + often provide Data Lakes
            + heavy-weight tools that are scalable and high-speed
            + specially designed programming tools and skills
            

# Structured Database Concepts

+ Database Elements

    + Table <- collection of related data held in a DB
        + should NOT contain mixture of data
        + should ONLY contain related data
    + Row <- also called record, tuple, or data set
    + Field <- also called column, data values, or predictor
    
+ DB Designs

    + Database Schema <- blueprint of the tables and fields and relationships
    + Data Model <- higher level design
    + Relationship <- how fields between tables are linked
    + keys <- determine how the table is indexed and how things are related (how tables are linked together)
        + need some kind of key to link to other tables

+ Data Dictionary
    + Stores the description of tables in a database
    + And databases in an organization
    + AKA data catalog, metadata repository
    

# Database Management Roles

+ Oversight

    + CIO
        + interfaces with the board
        + responsible for ensuring all data is properly protected 
    + CTO
        + oversees grand plan of how everything fits together
        + People have access to all data schemas, models, integration
        + good place for analysts to get ingrained with
    + DB Architect aka Application Architect
        + understands every application within the company
        + the entire flow of data from origin to passing around to other parts of orgnaization
        + transaction data flows to other applications
        + architect must know where the data is created and where it ends up
        + manage things within the DB environment
    + Data Security Architect
        + manage data privacy issues
        + what's accessed, who access it, and how is it accessed
        + ensure data is properly controlled

+ Daily Hands on

    + DB Administrator
        + person responsible for 1 or more DB's of a particular product type
        + ensure DB runs properly
        + ensure the right people have the right access to products
        + ensures DB is backed up and safe
    + DB Security Administrator
        + similar to security architect
        + grants rights to data
    + DB Designer / Developer
        + not concerned with daily upkeep of DB
        + takes user specifications to develop the right kind of DB with the right kind of structure, according to grand plan
    + Data Integration Engineer
        + manage data warehouse and approves requests
    + Application Programmer
        + write / develop applications
        + come up with specifications of what users want
        + work with DB Designer / Developers to write the application

+ DB Architecture

    1. Transaction systems
    2. Operational DBs
    3. ETL processes
    4. Data Warehouse
    5. Data Marts
    6. Business Intelligence Environment
    7. Information

# Databases & Data Analytics

Data analyst-like roles

+ Data Scientist <- full spectrum
+ Data Wrangler <- dirty data

    + aka data munging
    
+ Data Analyst <- all about insights

    + analysis via statistical modeling
    + drive insights and decision making 
    
+ Report Designer <- make it understandable

    + make reports because they understand the data
    + take raw data to build excellent visualizations to use for data storytelling
    
+ Data Mining

    + the data needs to be accurate!
    + find *hidden patterns and relationships* in large DBs and infer rules from them to predict future behavior
    + *non-trivial extraction* of implicit, previously unknown and potentially useful information from data
    + Exploration & analysis by *automatic/semi-automatic means* of large quantities of data in order to discover meaningful patterns
    + Data Mining <- ML > Pattern recognition > Statistics > Visualization > High-performance computing > DB technology > algorithm > applications

+ Data Mining Life-cycle

    1. Business understanding (domain / context)
    2. Data understanding (EDA)
    3. Data preparation (wrangling)
    4. Modeling
    5. Evaluation
    6. Deployment

+ Assignment 01-03-01 (unstructured data analysis)

    + look at canvas
    + various career sites
        + indeed / glassdoor / LI / google
    + 3-5 different groups
    + Paragraph: 
        1. What gorup the document is for
        2. Why these postings fit in the group
        3. Identify any postings that could fit into multiple groups
        4. List several terms and phrases (from the posting) that are new to you
            + acronyms
            + phrases / words
            + technologies / languages
            
            
# Albers Virtual Desktop

+ access to Albers desktop
+ using VMWare client to login
+ successful login to virtual desktop
+ verified all necessary software is installed and available
      

# SQL Server Local

+ No thanks!


# Database Review - Assignment

+ Database <- collection of data sets stored in a systematic way
+ Data types: structured / semi-structured / unstructured (idk what the structure is or can't control it)
+ Structured data

    + schema-based, relational DBs
    + traditional business DBs
    + known and maintained format
    + products / sales / inventory / warehouse
    + DBMS required
        + heavyweight, server-based systems
        + controls all access and data integrity
        + fast and scale upward
        
+ DB Elements

    + table <- collection of related data held in a DB
    + row <- aka record, tubple, data set
    + field <- column, data values, or predictor
        + types of data
    + schema
    
+ DB example: manages sales and returns

    + can't change DB much once it's put in place
    
+ Updating Frequency

    + Database
        + Batch Processing <- collects all transactions for a time period, then processes the data and updates the data store.
            + ran at some set recurrence (eg. "every 24 hours) 
        + OLTP <- Online-Transaction-Processing - processes each transaction as it occurs (real-time)
            + does not mean "cloud" 
            
            
# 01-06-01 - DBMS Overview

+ Database must be organized, controlled, and secure
+ DBMS

    + System software <- creating and managing databases and data
    + Provides users and programmers with a systematic way to create, retrieve, update, and manage data
    + Ensures data is clean
    + Examples for Structured Relational DBs: 
        + SQL Server
        + MySQL
        + Oracle
        + PostgreSQL
        + IBM DB2
        + Amazon RDS
        + Sybase

+ DBMS Software is the link between application servers and different databases

    + Ensures clean and updated data


# 01-06-02 - Database Hosting

+ some way that we host a database
+ Data Center made up of racks and servers
+ hosting a database means that it resides on a server in a data center so that it's properly managed
+ DBMS must host the database as well as: 

    1. Data Manipulation (ACID)
    2. Performance
    3. Availability
    4. Security & Compliance

+ Database Hosting <- here's the DB, it sits out there on the DB server, and it's managed by the DBMS


# 01-06-03 - ACID - Data Manipulation

+ ACID <- a set of conditions that guarantee the validity of a transaction 

    + Everything we do with the data must fall within ACID
    + Ensures each transaction follows the ACID conditions
    
+ Transaction <- credit card purchase, submit timesheet, submit insurance claim, manufacturing equipment measuring sensor readings and sends to a log, heart rate monitor and submits to EMR's, buying/selling stocks

+ Atomicity <- guarantees each transaction is a single unit, unaffected by other transactions

    + Bank withdrawal
    + Ensures all transactions are treated separately

+ Consistency <- guarantees that a transaction follows all the rules or won't be applied

    + Amount is a currency and dates are valid
    + All about rules
    + Can't do a query to submit data to a DB that doesn't follow the 'date' and 'currency' rules

+ Isolation <- guarantees transaction happen sequentially, rather than at the same time

    + withdrawals happen in order

+ Durability <- guarantees once a transaction is committed it remains part of the data, regardless of system failure

    + Transaction is written to a hard drive
    
+ DBMS Query MUST pass the ACID test

    + Update
    + Insert
    + Delete

+ Control constraints

    + Keys - ensures uniqueness (primary keys)
    + Referential Integrity - ensure validity
    + Data parameters - ensure correctness
    + Trigger - ensure follow on processes are completed
    + Synchronization - transactions in databases are in sync
    
+ Everything comes into play with how you do your queries

# 01-06-04 - Performance

+ regarding "how well" the server delivers what's needed for applications and users that use the DB
+ Performance

    + Concurrency <- how many people/applications will be using the DB at the same time
    + Scale <- what size does the DB need to be in order to deliver the performance needed
    + add additional application servers to scale up and meet "load balancing" needs
        + get rid of the old machine and install a bigger machine with more capability
        + memory 16GB - 128GB (more for data queries & analysis)
        + processors 4 cores - 32 cores (more for heavy calculations and processing)
        + Input/Output Processing 2400 - 64000 (more for back and forth processing to disk such as making frequent updates which leads to heavy workload)
        + Storage 128GB - 1TB (SSDs (Solid State Disks $$$) for read/write speeds)
        
+ Pokemon Go estimated 1MM downloads on Day 1. They had 6MM downloads, and 100MM users in the first month. They had to scale up quick in order to retain those users        

  
# 01-06-05 - Availability 

+ Availability <- the data is accessible
+ Techniques

    + Failover - replication / mirroring. Make a copy in case the first server fails
    + Recovery - replication / logs. Must be able to recover the data.
    
+ Uptime - can't have 100% availability. Servers must be updated at some point

    + 99% uptime == 87 hours per year downtime
    + 99.9% uptime == 8 hours per year downtime
    + 99.99% == 52 minutes per year downtime
    + 99.999% == 7.5 minutes per year downtime
    + Four 9's or Five 9's are for the most essential services
    
+ Replication / Mirroring

    + Primary replica
    + Secondary replicas - exact duplicates of primary
    
+ High-availability <- synchronous replicas \$\$\$

    + when a transaction comes in and gets written to the primary DB, it must be replicated to the secondary DB's with confirmation that it's been successfully written to the Primary
    
+ Recovery servers <- asynchronous replicas

    + typically smaller than primary / secondary DB servers
    + used just in case of a disaster
    
+ Availability and Recovery

+ High Availability (expensive option)

    + Synchronous replicas (must complete the transaction)
    + Must match the primary replica
    + Expensive
    
+ Recovery (Disaster)
    
    + Asynchronous replicas (could lose some data)
    + TYpically smaller servers
    + In a geographically different location
    + Often used for backups and BI applications
    
+ Tradeoffs of availability of a DB vs. how much you can afford \$\$\$
+ Primary server is where the $ is made - don't want to do analytics on primary server because that's where people are buying stuff

    + Do analytics on recovery servers since it's a replica of the primary
    + Analytics and queries should not mess with Production server (primary)
    

# 01-06-06 - Security and Compliance

+ Ensures data privacy, adherence to data governance compliance
+ Ethical reasons

    + customers
    + employees
    
+ Regulations

    + Sarbanes-Oxley Act (SOX)
    + HIPPA - Health data
    + GDPR - General Data Protections Regulation
    + Gramm-Leach-Bliley Act (GLBA)
    + USA Patriot Act
    
+ Data Classification 

    + How do we know what data is restricted, needs to be restricted, or is publicly available
    + Data has different levels of classification
    + Access based on data classification (AUTHENTICATION)
        + User specific <- rights assigned to a specific user
            + possibly in a group (Finance, HR, etc.)
        + Application specific <- rights controlled through the application (service account)
            + Equipment sensor reading
            + Refrigerator
            + Where the application controls data access rights
        + Row-level <- prevents / grants access to specific rows
            + for a particular region or product line
            + employees in a specific department
            + controlled by a filter applied to a specific column
            + like putting a filter on the rows to display only the relevant information
        + Column-level <- prevents / grants access to sensitive columns
            + SSN, Salaray, Price, Forecast
            + Tied to user or application rights
            + based upon who you are, there are certain rules that drive what you're allowed to see
        + DBMS Managed!
    + Exposure (Data Loss Prevention) - make it difficult to be attacked by hackers
        + Encryption <- making data unreadable
            + At Rest
                + Protects data on the hard drive
                + DBMS encrypts before storing
                + DBMS unencrypts when reading
            + In Transit
                + Protects data between DBMS and user
                + DBMS encrypts data before sending to user
                + DBMS sends "key" to user to unencrypt
                + DBMS sends encrypted data and key separately to protect from interception
        + Masking / Obfuscation <- controlled by the DBMS
            + No chance of exposure (fully gated)
            + Masking will automatically mask specific information as designed
        

# 01-07-01 Data Marts



# 01-08-01 - Relational Model



# 01-08-02 - Relational Model Part 2



# 01-08-03 - Relationships





    








